server:
  port: 8085

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/viajes_bookings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.viajes.booking: DEBUG