server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/viajes_payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

stripe:
  api:
    key: sk_test_placeholder

logging:
  level:
    com.viajes.payments: DEBUG